### ISSUE TITLE
CF1/CA1: Replicate last changes to CP1/CA2

### ISSUE THREAD

**Issue by rualark** [rualark/MGen#1097]
- [x] Migrate all vector dpenalty calculations to a single function #1094
- [x] Optimize SAS correction by not evaluating melodies, that already have dpenalty larger than dpenalty_min #1079
- [x] Implement appending dpenalty calculation for SAS and SWA corrections #1093 
- [x] Add time limit for SAS correction #1057
- [ ] Animation during SWA and SAS correction
- [x] Implement cc_order (possibly implemented)
- [x] Implement and test corrections cc_order (possibly implemented)
