### ISSUE TITLE
Create list of typical issues and try to autotest them

### ISSUE THREAD

**Issue by rualark** [rualark/MGen#1131]
- [x] Always abort all algorithms if error>0 detected
- [x] Non-recommended or currently not working configuration options are used (s_len <> 1, best_rejected > 0, cantus_high=1, corrections>1 until harmony is fixed)
- [x] Changed rule id, that is already used in code, expected lyrics or false_positive config. This is rare because I try not to reassign rule id to a different rule. Especially now it is not recommended, because rule can be in some of rule lists. **Check if every rule in rule list exists.**
- [x] Required variables are prepared later in the sequence of functions in CF1/CP1 algorithms. SET_FLAGS, CLEAR_FLAGS, ASSERT_FLAGS
- [x] ASWA and SAS algorithms find different best results. For CA5 and CA3 this is a long test, but for cantus, CA1, CA2, CA4 this is fast
- [x] Trying to fire rules that were not loaded. ASSERT
- [x] Test if RuleParam[rset] is empty
- [x] Find how much flags are delayed in SAS emulator. Warn if flags are delayed more steps than expected - because this decreases performance.
- [x] Correction clib is too big
- [x] Wrong cf=high/low detection. Already a critical error in ExplodeCP
- [x] Unable to load melody. Autotested files should not contain any garbage that can be ignored. This means that when m_testing is set, you cannot easily ignore any melody.
- [x] Memory usage is too high
- [x] Wrong species detection. Currently error reporting is implemented in DetectSpecies

Paused:
- [ ] Wrong key detection. Not very important test, because key detection algorithm does not receive many updates. Currently in GetCPKey if key is not detected, error is fired.
- [ ] Generation results have same starting notes. Not implemented. Rare issue difficult to detect.
- [ ] Release and Debug builds give different results. This is a very rare bug.

Separate issues:
- [x] Setting too many flags in anflags (vector overflow) (#957)
- [x] Flags that do not have to fire - are fired (#1132)
- [x] In SAS flags are fireing that do not fire in final full-melody run (#1129)
- [x] Steps before fn or after ep2-1 are accessed or changed (#1133)

Already implemented:
- [x] Flags that have to fire - are not fired
- [x] Resulting vectors validation
- [x] File access validation
- [x] Configuration parameters checks and ranges validation
- [x] Unknown configuration parameters names
- [x] Crashes and thread hangs

**Comment by rualark** [comment]
Debugging FailMelodyHarm:
- Unlike main SAS loop, FailMelodyHarm never analyses full melody if previous analysis was unsuccessful. This is why there is nothing to compare like in SAS emulator.
